name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Deploy to server
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            git config --global --add safe.directory /pool/www/alakbaroff.com
            cd /pool/www/alakbaroff.com
            git fetch origin master
            git reset --hard origin/master
          EOF